### ISSUE TITLE
Use Case, Performance

### ISSUE THREAD

**Issue by MarkHerhold** [paulmelnikow/wabac#33]
Hey Paul, great to see another project from you.

I'm curious what data caching problem you built this for (e.g. what type of data, when/how it changes) and what an ideal usage pattern would look like.

I don't know how performant GCP's cloud storage is, so I'm curious to hear about what type of usage patterns work best.

**Comment by paulmelnikow** [comment]
Hey! Thanks for reaching out :)

My use case is a web cache. I'm attempting to write a library that extracts structured data about events from arbitrary web pages. I want to to be robust, and collect failure cases from users, which are then added to a regression test suite. I also want to create an easy-to-reason-about developer experience (e.g. to locally diagnose a failure that occurred in CI using the same version of the data). Finally, I don't want to fetch the data every time I run tests, both so I don't bother the websites and so the tests are reasonably fast.

I'm expecting to accompany this storage layer with a human management layer backed by a database, probably using Airtable. The examples will have effective dates: if a page once worked but no longer does, it will be omitted from future tests. The examples will have their extracted values stored alongside, also to be validated by the operator. And I'm thinking the failures got be logged to the same database to give the operator a chance to mark them "no longer valid."

I started this project a while ago and am just getting back to it, so some of the details are a little fuzzy. Let me know if I can explain that better.

This was my first time using GCS so it's hard to speak to it's performance characteristics yet! In part this is about GCS, though it's also about getting the abstraction right. If I had this working with GCS I think it would be pretty easy to back it by Redis instead, for example.
